version: '3.8'
services:
  init-db:
    image: mcapecci/init-cine-db:latest

  postgres_server:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: cine_db   
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - init-db

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres_server
    depends_on:
      - postgres_server
